### ISSUE TITLE
Invalid string interpolation applied to password

### ISSUE THREAD

**Issue by danielstreit** [dappnode/DAppNodePackage-prysm-pyrmont#12]
While setting up Prysm Pyrmont, I ran into an issue with an auto generated password, where it appears to attempt string interpolation on the password:

```
  {
    "level": "error",
    "timestamp": --------,
    "event": "packageInstall",
    "message": "Command failed: docker-compose -f dnp_repo/prysm-pyrmont.dnp.dappnode.eth/docker-compose.yml config\nThe aav variable is not set. Defaulting to a blank string.\nInvalid interpolation format for \"environment\" option in service \"validator\": \"WALLET_PASSWORD=C74$aav$#FQ0m6\"\n",
    "stack": "Error: Command failed: docker-compose -f dnp_repo/prysm-pyrmont.dnp.dappnode.eth/docker-compose.yml config\nThe aav variable is not set. Defaulting to a blank string.\nInvalid interpolation format for \"environment\" option in service \"validator\": \"WALLET_PASSWORD=C74$aav$#FQ0m6\"\n\n    at Object.<anonymous> (/usr/src/app/webpack:/src/utils/shell.ts:37:16)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/index.js:19333:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "args": [
      {
        "name": "prysm-pyrmont.dnp.dappnode.eth",
        "version": "0.1.0",
        "userSettings": {},
        "options": {}
      }
    ]
  }
```

The password in the log was randomly generated and is not in use in anything.

I was able to work around this by generating a different password that did not match the string interpolation regex.

**Comment by dapplion** [comment]
Please try again with latest version, it does not handle the password directly, but instead through the Prysm onboarding only. Re-open the issue if it persists
